services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_app_development
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  app:
    build:
      context: .
      target: dev          # <- usa o estágio dev 
      args:
        PRECOMPILE: "0"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/school_app_development
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  bundle:
  node_modules:
