services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_app_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d school_app_development"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  app:
    build:
      context: .
      target: dev         # usa o estágio dev do seu Dockerfile
      args:
        PRECOMPILE: "0"
    environment:
      RAILS_ENV: development
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      REDIS_URL: redis://redis:6379/1
      # RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}   # se precisar em prod/CI
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
  bundle:
  node_modules:
