# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "db") %>
  username: <%= ENV.fetch("PGUSER", "rails") %>
  password: <%= ENV.fetch("PGPASSWORD", "rails") %>
  pool: 10


development:
  <<: *default
  database: school_app_development


test:
  <<: *default
  database: school_app_test


production:
  primary: &primary_production
    <<: *default
    database: school_app_production
    username: school_app
    password: <%= ENV["SCHOOL_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: school_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: school_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: school_app_production_cable
    migrations_paths: db/cable_migrate
