name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: rails
          POSTGRES_DB: school_app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: rails
      PGPASSWORD: rails
      PGPORT: 5432

    steps:
      # Baixa o código
      - uses: actions/checkout@v5

      # Seta versão do Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      # Instala Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Ativa Corepack (necessário para Yarn no Rails 8+)
      - name: Enable Corepack
        run: corepack enable

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      # Prepara o banco de testes
      - name: Setup DB
        run: |
          bin/rails db:prepare

      # Roda lint (Rubocop, se estiver usando)
      - name: Run Linter
        run: |
          if [ -f bin/rubocop ]; then bin/rubocop || true; fi

      # Roda os testes
      - name: Run Tests
        run: |
          bin/rails test
